---
title: "Repro_Research_Week2"
author: "Chris Hunter"
date: "7/23/2017"
output:

  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
#library(knitr)
knitr::opts_chunk$set(echo = TRUE, options(scipen=999))

```
  
##**Loading and preprocessing the data**
  
```{r process}
library(dplyr)
library(ggplot2)
# read data and ignore all NA values
act <- read.csv("./activity.csv")
act_no_na <- complete.cases(act)
act_good <- act[act_no_na,]

# Calculate total, mean, and median steps grouped by date
act_good_byDay <- select(act_good, steps, date) %>%
  group_by(date) %>%
  summarize(total_steps = sum(steps), mean_steps = mean(steps), 
            median_steps = median(steps))

# Calculate mean steps by 5 minute interval
act_good_byInt <- select(act_good, steps, interval) %>%
  group_by(interval) %>%
  summarize(mean_steps = mean(steps))
```
  
--------
        
##**What is mean total number of steps taken per day?**  
  
```{r}

par(mar = c(5, 4, 2, 1))
hist(act_good_byDay$total_steps, col = "blue", xlab = "Total Steps", 
     main = "Total Steps By Day", breaks = 10, xlim = c(0, 25000))
  
mean_good <- as.integer(mean(act_good_byDay$total_steps))
median_good <- as.integer(median(act_good_byDay$total_steps))
```
    
The mean total steps for each day is **`r mean_good`**.  
       
The median total steps for each day is **`r median_good`**.
    
        
##**What is the average daily activity pattern?**  
  
```{r}
#create line plot to show avg steps by interval
ggplot(data = act_good_byInt, aes(x = interval, y = mean_steps)) +
geom_line(linetype = 4) + 
  ggtitle("Average Steps by Interval") +
  xlab("Interval") + ylab("Avg Steps") + theme_bw()

#find interval with max number of steps to display in markdown
high_step_int <- 
  act_good_byInt[act_good_byInt$mean_steps == max(act_good_byInt$mean_steps), 1]
```
    
###The interval with the highest average number of steps is **`r high_step_int`**.
         
             
           
##**Imputing missing values**
  
```{r}
#calculate total number of missing values to display in markdown.
num_na <- sum(!act_no_na)
```
  
###The number of rows with missing values is **`r num_na`**.
      
In order to handle the missing values, the mean for the 5 minute interval associated with the NA value will be substituted.

```{r}
act_repl_na <- act 
# replace NA with mean for 5 minute time interval
act_repl_na[is.na(act_repl_na), 1] <- 
  act_good_byInt[match(act_good_byInt$interval, act_repl_na$interval), 2]
# calculate total, mean, and median steps by date
act_repl_byDay <- select(act_repl_na, steps, date) %>%
  group_by(date) %>%
  summarize(total_steps = sum(steps), mean_steps = mean(steps), 
            median_steps = median(steps))

#hist plot to show total steps by each day
par(mar = c(5, 4, 2, 1))
hist(act_repl_byDay$total_steps, col = "blue", xlab = "Total Steps", 
     main = "Total Steps By Day", breaks = 10, xlim = c(0, 25000))

# display mean and median steps each day
mean_repl <- as.integer(mean(act_repl_byDay$total_steps))
median_repl <- as.integer(median(act_repl_byDay$total_steps))

```
     
The mean total steps for each day is **`r mean_repl`**. 
   
The median total steps for each day is **`r median_repl`**.
   

-----   
      
##**Are there differences in activity patterns between weekdays and weekends?**
```{r}
# create a factor variable denoting weekday or weekend and add to data set
weekday <- as.factor(weekdays(as.Date(act_repl_byDay$date)))
levels(weekday) <- c("weekday", "weekday", "weekend", "weekend", "weekday", "weekday", "weekday")

#combine factor with dataset
act_repl_weekday <- cbind(act_repl_na, weekday)

#  mean steps by interval and weekday/weekend
act_repl_byInt <- select(act_repl_weekday, steps, interval, weekday) %>%
  group_by(interval, weekday) %>%
  summarize(mean_steps = mean(steps))
 
#create plot to show avg steps by interval and by weekday/weekend
ggplot(data = act_repl_byInt, aes(x = interval, y = mean_steps)) +
geom_line(linetype = 4) + 
  ggtitle("Average Steps by Interval", 
          subtitle = "By Weekday/Weekend") +
  xlab("Interval") + ylab("Avg Steps") +
  facet_grid(weekday ~ . ) + theme_bw() +
  theme(strip.background = element_rect(fill = "wheat"))
        
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
